In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [255]:
dataset = pd.read_csv('indo_pak.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [256]:
print(X)


[[2017.    31.    23.    79.    82. ]
 [2021.    30.    22.4   79.    82. ]
 [2018.    19.3   20.9   69.     7. ]
 [2019.     9.3   17.4   57.    58. ]
 [2020.    13.7   19.9   66.    65. ]
 [2022.    30.7   24.1   84.    85. ]
 [2020.    12.    19.    58.    63. ]
 [2017.    12.7   19.5   65.    65. ]
 [2021.     5.    24.7   86.    87. ]
 [2018.    11.    18.2   58.    59. ]
 [2019.    31.1   23.5   82.    83. ]
 [2020.    27.7   21.9   76.    79. ]
 [2019.    11.9   18.6   57.    61. ]
 [2017.    15.9   20.4   67.    64. ]
 [2018.    10.    17.8   58.    59. ]
 [2021.    25.    21.4   73.    74. ]
 [2019.    31.1   23.5   82.    83. ]
 [2020.    13.7   19.9   66.    65. ]
 [2021.    25.    21.4   73.    74. ]
 [2018.    27.7   21.9   76.    79. ]
 [2017.     9.3   17.4   57.    58. ]
 [2022.     5.    24.7   86.    87. ]
 [2022.    30.7   24.1   84.    85. ]
 [2017.    15.9   20.4   67.    64. ]
 [2020.    12.    19.    58.    63. ]
 [2021.    31.    23.    79.    82. ]
 [2018.    1

In [257]:
print(y)

[53.3 52.8 65.5 62.5 64.8 40.  64.  64.4 80.3 63.3 43.6 51.4 63.7 65.2
 62.9 66.  43.6 64.8 66.  51.4 62.5 80.3 40.  65.2 64.  53.3 65.5 62.9
 64.4 63.7 63.3 52.8 43.6 80.3 65.2 62.5 66.  64.8 51.4 65.5 40.  64.4
 64.  63.3 53.3 52.8 62.9 63.7 66.  43.6 51.4 64.8 65.5 80.3 40.  64.
 64.4 62.9 63.7 63.3]


In [258]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X, y)

LinearRegression()

In [263]:
regressor.predict([[2024,0,30,79,82]])

array([86.10057749])

In [271]:
import joblib
joblib.dump(regressor, "pak.pkl")

['pak.pkl']

In [265]:
model = joblib.load("india.pkl")

In [266]:
model.predict([[2024,10,21,30,24]])

array([65.0032142])

In [267]:
model.predict([[2024,10,7,30,24]])

array([60.0684332])

In [268]:
model.predict([[2015,    12,    19.1 ,   6,    65.]])

array([48.35183818])

In [269]:
model.predict([[2024,10,7,97,96]])

array([70.46788889])

In [270]:
model.predict([[2024,10,21,97,96]])

array([75.40266989])